### ISSUE TITLE
When IAB and IESG are listed as authors, keep them as authors, not organizations

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#101]
As per https://github.com/ietf-tools/bibxml-service/issues/296 from @ajeanmahoney:

(This report should not be confused with #262, which is an issue with a different library)

For 35 RFCs in the IAB Stream, the Internet Architecture Board is listed as an _author_ (not an organization). (Note that the IAB no longer lists itself as an author in its RFCs, so this issue only impacts a subset of older IAB Stream documents.)

For 22 of those RFCs, the author information is presented as the following in rfc-index.xml:
```
<author>
  <name>IAB</name>
</author> 
```
For 11 of those RFCs, the author information in rfc-index.xml is the following:
```
<author>
  <name>Internet Architecture Board</name>
</author>
```

In the bib information returned from bib.ietf.org, this has been transformed into 
```
<author>
  <organization>Internet Architecture Board</organization>
</author>
```
Author information in a reference should match author information provided in the header of the RFC. For these IAB Stream documents, if rfc-index.xml specifies "IAB" as an author, then this should also be used in the bib data. If rfc-index.xml uses "Internet Architecture Board" for an author name, then this should be used in the bib data. This will let the bib data more closely match the information in the RFC header.

There are also a small number of documents that list the IESG (5 documents) or the Internet Engineering Steering Group (2 documents) as author. This information also needs to be passed though unmodified. 
 
Note: The following are unique to the RFC series, but using the bib-index.xml author information should work:

RFC 3716
rfc-index.xml: `<author><name>IAB Advisory Committee</author></name>`
bib.ietf.org:  `<author fullname="IAB Advisory Committee" initials="IAB" surname="Advisory Committee"/>`

RFC 4089 
rfc-index.xml: `<author><name>IAB and IESG</author></name>`
bib.ietf.org:  `<author fullname="IAB and IESG" initials="IAB" surname="and IESG"/>) `

**Comment by ronaldtse** [comment]
@andrew2net this means we just don't process them as organizations or extract initials:
* "IAB"
* "Internet Architecture Board"
* "IAB and IESG"
* "IAB Advisory Committee"
* "IESG"
* "Internet Engineering Steering Group"

**Comment by ronaldtse** [comment]
Actually see: https://github.com/ietf-tools/bibxml-service/issues/296#issuecomment-1247861503

**Comment by andrew2net** [comment]
The contributor with description ["BibXML author"](https://github.com/relaton/relaton-data-rfcs/blob/c834e5221db03722dc45bad71ad1644e8bdca983/data/RFC4089.yaml#L47-L53) now rendered in BibXML output as:
```xml
<reference anchor="RFC.4089" target="https://www.rfc-editor.org/info/rfc4089">
  <front>
    <title>IAB and IESG Recommendation for IETF Administrative Restructuring</title>
    <author role="editor" fullname="S. Hollenbeck" initials="S." surname="Hollenbeck">
      <organization/>
    </author>
    <author fullname="IAB and IESG"/>
    <date year="2005" month="May"/>
    <abstract>
      <t>This document describes a joint recommendation of the Internet Architecture Board and the Internet Engineering Steering Group for administrative restructuring of the Internet Engineering Task Force.  The IETF Chair declared that the IETF had consensus to follow this recommendation on November 11, 2004.  Further work has been done to revise and refine the structures proposed.  The recommendation is being published for the record.  This memo provides information for the Internet community.</t>
    </abstract>
  </front>
  <seriesInfo name="DOI" value="10.17487/RFC4089"/>
  <seriesInfo name="RFC" value="4089"/>
</reference>
```

**Comment by ronaldtse** [comment]
@andrew2net can I confirm that relaton-data-ietf has been updated as such? Where is this implemented?

1. relaton-ietf conversion of rfc-index.xml into relaton-data-ietf
2. conversion of relaton-data-ietf into bibxml?

**Comment by andrew2net** [comment]
@ronaldtse we don't use the relaton-data-ietf anymore. The relator-data-rfcs has been updated.
It's implemented:
1. In relaton-ietf v 1.13.2 conversion of rfc-index.xml into relaton-data-ietf. Certain author names are parsed as [organizations](https://github.com/ietf-tools/relaton-data-rfcs/blob/1263cfc0f52b01ead62c2d0861cacd92b859e4e8/data/RFC4089.yaml#L47-L53) and description "BibXML author" is added to contribution role.
2. In relaton-bib v 1.13.7. BibXML renderer is updated to output organization contributor with role description "BibXML author" like `<author fullname="IAB and IESG"/>`.
3. In relaton-bib v 1.13.7. BibXML parser is updated to parse authors like `<author fullname="IAB and IESG"/>` with certain names as organization contributor with role description "BibXML author".
