### ISSUE TITLE
Inconsistent role structure

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-ietf#105]
See this example:

https://github.com/ietf-tools/relaton-data-rfcs/blob/6a93fd877de9e81958d1560410a0e3035b46bbd9/data/RFC4052.yaml#L21-L53

`role` is specified as a string for the first contributor, and as an object for the second.

`relaton-py` expects a string. According to the spec, it should be an object. We’ll up-convert the string to an object on BibXML service’s side before `relaton-py` is invoked, but YAML should probably specify an object in the first place.

cc @andrew2net

**Comment by strogonoff** [comment]
NB: `relaton-py` updated its definition of roles in https://github.com/relaton/relaton-py/commit/19b697a06798772c23ae0e6326b990addaeb8050, BibXML service will upconvert the role to this model if it’s a string.

**Comment by ronaldtse** [comment]
@strogonoff this particular issue will go away when #103 is implemented.

**Comment by ronaldtse** [comment]
Actually:
> role is specified as a string for the first contributor, and as an object for the second.

This is a structural inconsistency and should be addressed here.

**Comment by andrew2net** [comment]
Fixed https://github.com/ietf-tools/relaton-data-rfcs/blob/318e3827787d358e4b77d836c7ecda88baa081f6/data/RFC4052.yaml#L23-L58
