### ISSUE TITLE
(URGENT) Structural discrepancies in Relaton-IETF data files

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#107]
From https://github.com/relaton/relaton/issues/108

There are structural discrepancies reported by @strogonoff.

> * [RFCS](https://raw.githubusercontent.com/ietf-tools/relaton-data-rfcs/main/data/RFC0001.yaml):
> 
> ```
> contributor -> 0 -> person -> name -> given -> forename -> 0
>   Forename.__init__() missing 1 required positional argument: 'content' (type=type_error)
> contributor -> 0 -> person -> name -> given -> forename -> content
>   str type expected (type=type_error.str)
> ```

> * [ID](https://raw.githubusercontent.com/ietf-tools/relaton-data-ids/main/data/draft-ayers-low-power-interop-02.yaml):
> 
> ```
> contributor -> 0 -> person -> name -> given -> forename -> 0
>   Forename.__init__() missing 1 required positional argument: 'content' (type=type_error)
> contributor -> 0 -> person -> name -> given -> forename -> content
>   str type expected (type=type_error.str)
> ```

**Comment by ronaldtse** [comment]
This also:

>  * [MISC](https://raw.githubusercontent.com/ietf-tools/relaton-data-misc/main/data/reference.W3C.soap11.yaml):
> 
> ```
> contributor -> 0 -> person -> name -> given -> forename -> 0
>   Forename.__init__() missing 1 required positional argument: 'content' (type=type_error)
> contributor -> 0 -> person -> name -> given -> forename -> content
>   str type expected (type=type_error.str)
> ```

**Comment by andrew2net** [comment]
@ronaldtse as per https://github.com/relaton/relaton-ietf/issues/99#issuecomment-1216885154 the `forename` element can have `initial` only, without `content`.
