### ISSUE TITLE
Handling the 'publisher' in BibXML

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#112]
From @rjsparks:

This went wrong for us - publisher is not really welcome here - see https://github.com/ietf-tools/bibxml-service/issues/321

_Originally posted by @rjsparks in https://github.com/relaton/relaton-ietf/issues/98#issuecomment-1319184508_

Originally from @ajeanmahoney at https://github.com/ietf-tools/bibxml-service/issues/321

The addition of the following <author> information to RFC references is incorrect:
```
<author>
<organization>RFC Publisher</organization>
</author>
```
See, for example, https://bib.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml

Please revert.

**Comment by ronaldtse** [comment]
This has been implemented by @andrew2net at c19a572acd5f63d3ceb61405667dcbf2cbc5e4d7 . Thanks!

**Comment by andrew2net** [comment]
@ronaldtse can we close this issue?

**Comment by ronaldtse** [comment]
@andrew2net are we able to add Publisher information for Relaton data but skip that in BibXML?

**Comment by ronaldtse** [comment]
Ping @opoudjis

**Comment by andrew2net** [comment]
> @andrew2net are we able to add Publisher information for Relaton data but skip that in BibXML?

@ronaldtse yes, we can add "RFC Publisher" to relaton data and remove publishers with the name when rendering BibXML.
There aren't any documents with the author name "RFC Publisher" in the source https://www.rfc-editor.org/rfc-index.xml, but in case documents with such a publisher will be added to the source later it will be missed in BibXML output.

**Comment by andrew2net** [comment]
> @andrew2net are we able to add Publisher information for Relaton data but skip that in BibXML?

@ronaldtse done in v 1.14.2

**Comment by rjsparks** [comment]
@andrew2net : I think the attempts at versioning didn't work? We haven't (and won't for a week or more) deployed any updated code at bibxml.ietf.org, yet the effects of the change to the datasource have leaked through there.

**Comment by rjsparks** [comment]
See https://github.com/ietf-tools/bibxml-service/issues/325
