### ISSUE TITLE
(URGENT) Crash in handling IETF pubids

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#113]
There are 2 issues here:

1. Relaton-bib complains that the contributor type is invalid
2. Crash with wrong Ruby object types

Happens at https://github.com/metanorma/mn-samples-ieee-private

```
[relaton-bib] Contributor's type "authorizer" is invalid.
[relaton-ietf] ("RFC 3406") found RFC 3406
[relaton] ERROR: RFC 3406 -- undefined method `match' for {:content=>"namespaces"}:Hash

      if cnt.match(regex)
            ^^^^^^
```

**Comment by andrew2net** [comment]
@ronaldtse this issue is fixed in the last relaton version
