### ISSUE TITLE
Regression of "RFC Publisher" shown on the IETF BibXML service

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#114]
From: https://github.com/ietf-tools/bibxml-service/issues/325

This issue regressed because Relaton-IETF included the "RFC Publisher" for non-IETF data, and that version pinning was not implemented for https://github.com/ietf-tools/relaton-data-rfcs.

The issue is in particular is shown here:
* https://github.com/ietf-tools/relaton-data-rfcs/blame/c4ec20252ecc73f0cf33ad3ca8775f63137839b0/data/RFC8288.yaml#L52-L56

There are two ways we can fix this:
1. Option 1. For the IETF version of relaton-data-rfcs, do not insert "RFC Publisher" at all. This will avoid this issue. This requires relaton-ietf to have a command line that differentiates Relaton usage vs IETF usage.
2. Option 2. Use the same data set for both IETF and Relaton, but in the BibXML service, exclude the "RFC Publisher" (and others) according to IETF-specific rules.

@andrew2net @strogonoff @stefanomunarini Please your opinion here on the way forward.

(Original fix: https://github.com/relaton/relaton-ietf/issues/112)

**Comment by ronaldtse** [comment]
Can this be closed now? The source issue has been closed.

**Comment by stefanomunarini** [comment]
@ronaldtse this is completed. Closing
