### ISSUE TITLE
Build failing on AppVeyor Ruby 2.3 and Ruby head

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#16]
Build: https://ci.appveyor.com/project/ribose/ietfbib/builds/23658405

Can we either fix them, or ignore these test results on AppVeyor?

**Comment by CAMOBAP** [comment]
For now all Ruby head build for all repos don't work on Appveyor,

@ronaldtse  should we fix it https://github.com/metanorma/metanorma-build-scripts/issues/2

Regarding 2.3 there is some instability, I will check

**Comment by ronaldtse** [comment]
Yes please help fix this issue by disabling AppVeyor `trunk`. Thanks!

**Comment by CAMOBAP** [comment]
Fixed
