### ISSUE TITLE
Add missing fields to IETFBib::Scrapper::bibitem

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-ietf#17]
I've released iso-bib-item, but that means that the relaton and metanorma-standoc rspec now is failing on ietfbib, because mandatory fields such as script are not supplied. Could you patch those missing fields in, and I can then do a release of ietfbib?

**Comment by andrew2net** [comment]
@opoudjis I will do it tomorrow.

**Comment by andrew2net** [comment]
@opoudjis in https://github.com/metanorma/metanorma-model-iso/blob/master/grammars/ietf.rnc we have ` (btitle+ | formattedref)`, `copyright` and `editorialgroup` mandatory fields only. I added `script` field with "Latn" value. What value should we use for `copyright` and `editorialgroup` fields?
```
BibData =
    attribute type { BibItemType }?,
    (btitle+ | formattedref), abbrevtitle?, 
    bsource*, docidentifier*, docnumber?, bdate*, contributor*,
    edition?, version?, biblionote*, language*, script*, 
    abstract*, status?, copyright, docrelation*, series*, editorialgroup, ics*,
    ipr?, iprExtract?, submissiontype?, area*, keyword*, consensus?
```

**Comment by opoudjis** [comment]
For copyright, the copyright holder is the IETF. Strictly speaking, the copyright statement is:

````
  Copyright (c) 2016 IETF Trust and the persons identified as the
   document authors.  All rights reserved.
````

so:

````
 <copyright>
    <from>{year}</from>
    <owner>
      <organization>
        <name>Internet Engineering Task Force</name>
        <abbreviation>IETF</abbreviation>
      </organization>
    </owner>
  </copyright>
````

There are distinct editorial groups for different RFC publications, the workgroup that each publication belongs to; but that information is not included in the online bibliographies.

With some reluctance, I'm making the editorialgroup optional in the grammar. Don't populate it for IETF.
