### ISSUE TITLE
Citing Internet Drafts `draft-*`

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#2]
Other than IETF RFCs, we also need to cite IETF Internet-Drafts (documents with name `draft-*`).

As described here: https://xml2rfc.tools.ietf.org/

Both links work, probably use the latter one:
* http://xml2rfc.ietf.org/public/rfc/bibxml3/
* http://xml2rfc.ietf.org/public/rfc/bibxml-ids/

Examples:
* http://xml2rfc.ietf.org/public/rfc/bibxml3/reference.I-D.example-name.xml
* http://xml2rfc.ietf.org/public/rfc/bibxml3/reference.I-D.draft-example-name-99.xml

Note: Leave `draft-` off when referencing a generic draft name, and add `draft-` when referencing a specific version of an internet-draft.

**Comment by andrew2net** [comment]
@ronaldtse as I understand we need fetching not only documents with a name `draft-*` but also., all  `reference.I-D.example-name.xml` documents, do we?
So the difference between RFC code `RFC.example-name` and Internet-Drafts code `I-D.example-name` in their prefixes (RFC or I-D).

Suggest if we call search with RFC prefix
```
RfcBib::RfcBibliography.search 'RFC 8341'
```
then the RfcBib retrieves  IETF RFC. If call search with I-D prefix
```
RfcBib::RfcBibliography.search 'I-D.-burger-xcon-mmodels'
```
then RfcBib retrieves IETF Internet-Draft.

**Comment by ronaldtse** [comment]
The `draft-*` documents are identical to `I-D.*` documents, so we just need to recognize them properly to fetch them. We can use separate RegEx patterns to match these.

We should be a relaton gem (https://github.com/riboseinc/relaton) that allows registration of each type of bib-item gem (i.e. relaton-iso, relaton-rfc, relaton-gb, etc) , and when you do a `Relaton.search 'RFC 8341'` will return a `Relaton::BibItem` model with its content.

2 questions:
1. @andrew2net could you help create the `relaton` gem? This gem should also handle caching.
2. @andrew2net / @opoudjis should we rename the `*bib` gems (isobib, rfcbib, ...) into `relaton-*` gems? Or keep them separate?

**Comment by andrew2net** [comment]
@ronaldtse 
1. yes we could create the `relation` gem which recognizes a type of document and fetch using appropriated `relation-*` gem.
2. I think we could rename `*bib` gems but should keep them separated.

**Comment by ronaldtse** [comment]
1 & 2 both agree. Thanks!
