### ISSUE TITLE
Parse a file locally

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-ietf#20]
download this file https://github.com/usnistgov/ACVP/blob/master/src/draft-celi-acvp-sha-00.xml, and use `relaton-ietf` to create the relaton XML
```ruby
RelatonIetf::IetfBibliography.from_rfcxml(File.read(filename)).to_xml
```

**Comment by ronaldtse** [comment]
@andrew2net thanks for posing.

BTW, this name spacing is a bit strange: `Relaton::RelatonIetf`. Why can't we just have `Relaton::BibProvider::Ietf` or something like this? (`BibProvider` or `Provider` for bibliography information provider)

**Comment by andrew2net** [comment]
@ronaldtse the `relaton-ietf` gem has a `RelatonIetf` namespace, and we have an `IetfBibliography` module in the namespace which searches and gets documents.
`Relaton` is a namespace of `relaton` gem.
I think we should create the parser in `relaton-ietf` gem. Do you want to use `relaton`'s namespace in `relaton-ietf`?

**Comment by ronaldtse** [comment]
`relaton-ietf` gem implies `Relaton::Ietf` namespace. `relaton_ietf` implies `RelatonIetf`.

For example, `require 'relaton-ietf'` can load `relaton/processor/ietf.rb` and `ietf_bibliography.rb`.

I want to use `Relaton` namespace rather than `RelatonIetf`.

**Comment by andrew2net** [comment]
@ronaldtse [document](https://github.com/usnistgov/ACVP/blob/master/src/draft-celi-acvp-sha-00.xml) doesn't have `/reference[@anchor, @target]` element.
```
<reference anchor="RFC1909" target="https://www.rfc-editor.org/info/rfc1909">
...
```
 It has `/rfc[@category, @docName, @ipr]` instead.
```
<rfc category="info" docName="draft-ietf-acvp-subsha-1.0" ipr="trust200902">
...
```
We get `id` form attribute `@anchor` and `link` form attribute `@target`. We can ommite `link`. Could we use `@docName` attribute as `id`?

**Comment by ronaldtse** [comment]
Ahhh right. RFC XML is different from RFC BIBXML — BIBXML (our term for it) is part of RFC XML. 

Yes, we can take the docName as document ID, it is the correct attribute.

**Comment by ronaldtse** [comment]
@andrew2net could you also let me know how to use this from a CLI perspective? Maybe in `relaton-cli`. Thanks :wink:

**Comment by andrew2net** [comment]
@ronaldtse see it here https://github.com/metanorma/relaton-ietf#parse-a-file-locally

**Comment by ronaldtse** [comment]
@andrew2net could you help make this function available via Relaton CLI?

It currently supports `extract` functionality of a file and also of directories:
https://github.com/metanorma/relaton-cli#relaton-extract
