### ISSUE TITLE
No longer parsing DOI identifiers?

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-ietf#25]
In rspec of metanorma-standoc, I notice that you are no longer retrieving the DOI identifier:

metanorma-standoc, spec/asciidoctor-standoc/refs_spec.rb, line 396:

````
    <docidentifier type="IETF">RFC 8341</docidentifier>
 -  <docidentifier type="DOI">10.17487/RFC8341</docidentifier>
````

Is this a deliberate choice? If not, the DOI docidentifier should be restored.

**Comment by andrew2net** [comment]
It was from beginning. I don't remeber why.
https://github.com/metanorma/relaton-ietf/blob/46fd3f0c931a10d860ed83cd92fb707ea5df975e/lib/relaton_ietf/scrapper.rb#L212

**Comment by opoudjis** [comment]
As far as I can tell, you have just fixed this. Close if so.
