### ISSUE TITLE
Absorb RFC bib fetching / caching / citation functionality from `asciidoctor-rfc`

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#3]
We're going to move all these functionalities into this gem.

Re: https://github.com/riboseinc/asciidoctor-rfc/issues/104

**Comment by andrew2net** [comment]
@ronaldtse I'm looking through the `metanorma-ietf` code. As I see it makes XML from `Asciidoctor::Document` and adds references to it.
Do we need to use 'relaton' to fetch the references and store them into a cache?
