### ISSUE TITLE
add anchor as identifier

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-ietf#32]
In metanorma-ietf, we have a ticklish problem. As you know, XML RFC fragments are assumed to be included from online source; as a result, any relaton source is ignored, and replaced with an `<xi:include>`. However, that means that the IDs of XML RFC fragments are in fact hard coded into the target document, and need to overwrite any anchors the user has provided.

So the user is free to reference RFC 7253 as `* [[[abc,RFC 7253]]]`. But in the output RFC XML I generate, that "abc" anchor *must* be replaced with RFC 7253, since that is what the RFC XML fragment fetched online will use.

In order to allow me to do this postprocessing, I need you to add to relaton-ietf the anchor of the fetched RFC XML, as a distinct document identifier, say of type "rfc-anchor". So, when you process

https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.7253.xml

````
<reference anchor="RFC7253" target="https://www.rfc-editor.org/info/rfc7253">
...
</reference>
````

I need the bibitem returned by relaton-ietf to include `<docidentifier type="rfc-anchor">RFC7253</docidentifier>`.

I'd like to release this gem fairly soon, so if possible, I'd like this by next week: it should not represent a big addition.

**Comment by ronaldtse** [comment]
@opoudjis 

> XML RFC fragments are assumed to be included from online source;

I think this assumption has to go, the MN XML should already be the canonical source of references. There must be a way to cancel out xml2rfc's behavior that is irrelevant to us.

**Comment by andrew2net** [comment]
@opoudjis we have `<docidentifier type="IETF">RFC 8341</docidentifier>` already. The only difference is a space between a prefix and a number. Could you use it? The space added programmatically, I think we can remove it if you need.

**Comment by opoudjis** [comment]
I do not want to trust IETF that the anchor will always be derived from the identifier in this way, since they have hardcoded the anchor; and Internet Draft identifiers may also work differently. Please create the distinct identifier.
