### ISSUE TITLE
Cite specific drafts of Internet Drafts

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-ietf#33]
It should be possible to cite a distinct version of an Internet Draft. The versions (drafts) of the Internet draft do not have distinct screen-scraped files; but they do have distinct document identifiers.

The screen-scraped file for an Internet Draft always has a hard coded version number at the end of the identifier and URL:

IETF(I-D.abarth-cake)

retrieves:

https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.abarth-cake.xml

````
<reference anchor="I-D.abarth-cake">
<front>
<title>Origin Cookies</title>
<author initials="A" surname="Barth" fullname="Adam Barth">
<organization/>
</author>
<date month="March" day="5" year="2011"/>
<abstract>
<t>
This document defines the Origin attribute for cookies, which lets servers harmonize the security policy of their cookies with the widely used same-origin policy. Origin cookies provide both confidentiality and integrity, unlike the Secure attribute, which provides only confidentiality.Editorial Note (To be removed by RFC Editor) If you have suggestions for improving this document, please send email to <mailto:http-state@ietf.org>. Further Working Group information is available from <https://tools.ietf.org/wg/httpstate/>.
</t>
</abstract>
</front>
<seriesInfo name="Internet-Draft" value="draft-abarth-cake-01"/>
<format type="TXT" target="http://www.ietf.org/internet-drafts/draft-abarth-cake-01.txt"/>
</reference>
````

If a request is issued for an Internet Draft, suffixed by "-nn" (e.g. `IETF(I-D.abarth-cake-02)`), e.g. we expect the final "-nn" in the document identifier, `<seriesInfo name="Internet-Draft" value="draft-abarth-cake-01"/>`, and the URL, `<format type="TXT" target="http://www.ietf.org/internet-drafts/draft-abarth-cake-01.txt"/>`, to be replaced with the numbers supplied by the user: draft-abarth-cake-02 in both cases in any generated Relaton XML. 

I will also be declining to replace any such references with an external include in processing the generating XML.

**Comment by andrew2net** [comment]
@opoudjis I'm not sure I understand the correct. Does it mean user allow to add any final `-nn` and we have to replace identifier's and URL's final `-nn` with the user's one?

**Comment by andrew2net** [comment]
We didn't map the `reference/format` yet https://github.com/relaton/relaton-ietf/issues/1#issuecomment-396580005
So we don't parse it now.

**Comment by opoudjis** [comment]
First question: yes.  You allow the user to specify the final -nn.

Second question: The `reference/format/@target` and `reference/format/@type` tag should be parsed after all, to be the uri of the document. They should only be present for internet drafts.
