### ISSUE TITLE
Unable to fetch document I-D.draft-ietf-calext-eventpub-extensions

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#40]
This document clearly exists:
https://datatracker.ietf.org/doc/draft-ietf-calext-eventpub-extensions/

But I'm getting this:

```
[relaton-ietf] ("IETF I-D.draft-ietf-calext-eventpub-extensions") fetching...
Bibliography: Could not retrieve IETF I-D.draft-ietf-calext-eventpub-extensions: no access to online site
```

**Comment by ronaldtse** [comment]
@andrew2net can you help here? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse seems the latest version is published under "I-D.ietf-calext-eventpub-extensions" reference. Specific version is published under "I-D.draft-ietf-calext-eventpub-extensions-{ver}". However, relaton-ietf doesn't support version-specific references. Should we implement it?

**Comment by ronaldtse** [comment]
Aha, yes we should implement the “no version” to point to the latest version. Thanks!

**Comment by andrew2net** [comment]
Use "IETF I-D.ietf-calext-eventpub-extensions" reference instead of "IETF I-D.draft-ietf-calext-eventpub-extensions"

**Comment by ronaldtse** [comment]
Can we accept both? It’s really hard to know what to use and what not to use. Can you also help update documentation? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse yes we can update script to use both links. Which documentation do we need to update?
