### ISSUE TITLE
Implement IETF WG fetching via GHA cron

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#43]
We need a separate relaton-data-ietf repository to store IETF information. Their endpoints often go offline and affects the reliability of Metanorma.

e.g.
https://github.com/Kritner/ACVP/pull/2/checks?check_run_id=1517259818

![image](https://user-images.githubusercontent.com/11865/101484953-673ea080-3995-11eb-8de7-7c985694c35f.png)

Ping @opoudjis : we should extract the current code out and ask Relaton to handle WG fetching?

**Comment by opoudjis** [comment]
OK, the code in metanorma-ietf involved is `cache_workgroup()` in https://github.com/metanorma/metanorma-ietf/blob/master/lib/asciidoctor/ietf/validate.rb . There is a cache meant to be created on first execution, but GitHub Actions testing creates it from scratch, and even with VCR caching, it is blowing up.

Let me know when you've taken care of it, and I'll call your routine instead.

**Comment by andrew2net** [comment]
@ronaldtse we have discussed [api.relaton.com](https://github.com/relaton/api.relaton.org) cache service. The secvice can solve the problem. In case the IETF enpoint go offline the secvice can provide documents from cache. Wha do you think?

**Comment by ronaldtse** [comment]
> @ronaldtse we have discussed [api.relaton.com](https://github.com/relaton/api.relaton.org) cache service. The secvice can solve the problem. In case the IETF enpoint go offline the secvice can provide documents from cache. Wha do you think?

Yes I agree. But can we also have a simpler solution that only uses Git/GitHub?

Remember we had the idea of Relaton being manager of bibliographic information? We can just do:

```
relaton add-repo https://github.com/relaton/relaton-bipm-data
relaton add-repo https://github.com/myorg/relaton-data
```

Then we can fetch the bibliographic data.

**Comment by andrew2net** [comment]
> Remember we had the idea of Relaton being manager of bibliographic information? We can just do:
> 
> ```
> relaton add-repo https://github.com/relaton/relaton-bipm-data
> relaton add-repo https://github.com/myorg/relaton-data
> ```

@ronaldtse I don't remember this idea. Could you give me a reference to the discussion?
