### ISSUE TITLE
IETF BCP 9 and similar references not fetched

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-ietf#44]
References like IETF BCP 9 (https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0009.xml) do not appear to be fetched by relaton.

The RFC XML of these uses referencegroup tags, containing other RFC XML references. Treat these as bibitems with "includes" relations to their component bibitems.

**Comment by andrew2net** [comment]
@opoudjis isn't this correct fetching `IETF BCP 9`?
```
pry(main)> require 'relaton_ietf'
=> true
pry(main)> item = RelatonIetf::IetfBibliography.get 'IETF BCP 9'
[relaton-ietf] ("IETF BCP 9") fetching...
[relaton-ietf] ("IETF BCP 9") found BCP 9
=> #<RelatonIetf::IetfBibliographicItem:0x007fa5a08e9408
...
pry(main)> item.docidentifier[0].id
=> "BCP 9"
```

**Comment by opoudjis** [comment]
Huh, I must have looked at the wrong file. Ok, closing, sorry.

**Comment by andrew2net** [comment]
@opoudjis but I think we should use the https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcsubseries source as a BCP, FYI, and STD source. I believe it's more reliable using XML sources instead of scraping HTML pages. And relaton-ietf doesn't fetch FYI and STD references yet. Do you agree?

**Comment by andrew2net** [comment]
> Treat these as bibitems with "includes" relations to their component bibitems.

@opoudjis Now relation type is "merges". Are you sure we need to change it to "includes"?

**Comment by ronaldtse** [comment]
> I think we should use the https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcsubseries source as a BCP, FYI, and STD source. I believe it's more reliable using XML sources instead of scraping HTML pages.

Fully agree, can you make a ticket for that?

> And relaton-ietf doesn't fetch FYI and STD references yet.

I think we should fetch those too, can you help make a ticket for that too?

Thanks!

**Comment by andrew2net** [comment]
> Fully agree, can you make a ticket for that?

@ronaldtse I can use this ticket, can't I?

**Comment by ronaldtse** [comment]
Thanks @andrew2net !

**Comment by opoudjis** [comment]
Sorry I didn't get to this, and yes, merges, and yes, that source should indeed be used.
