### ISSUE TITLE
IETF RPC request: specific organization names for exporting IEEE and W3C references

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#48]
From the RFC Production Center:

> RPC prefers simply "IEEE" for the organization. (Rationale: commonly known by "IEEE".)
> 
> e.g. preference for output such as
> 
>     [IEEE802.1Q-2011]
>               IEEE, "Local and Metropolitan Area Networks -- Media
>               Access Control (MAC) Bridges and Virtual Bridged Local
>               Area Networks", IEEE Std 802.1Q-2011, August 2011.
> 
> 
> Similarly, preference for "W3C" over "World Wide Web Consortium" in references to W3C documents.
> 
> Example of output from the existing citation library:
> 
>       [W3C.REC-xml11-20060816]
>               Paoli, J., Sperberg-McQueen, C., Yergeau, F., Cowan, J.,
>               Maler, E., and T. Bray, "Extensible Markup Language (XML)
>               1.1 (Second Edition)", World Wide Web Consortium
>               Recommendation REC-xml11-20060816, August 2006,
>               <http://www.w3.org/TR/2006/REC-xml11-20060816>.
> 
> Better as:
>
>       [W3C.REC-xml11-20060816]
>               Paoli, J., Sperberg-McQueen, C., Yergeau, F., Cowan, J.,
>               Maler, E., and T. Bray, "Extensible Markup Language (XML)
>               1.1 (Second Edition)", W3C Recommendation REC-xml11-20060816, 
>               August 2006, <http://www.w3.org/TR/2006/REC-xml11-20060816>.

Originally from https://github.com/ietf-ribose/bibxml-service/issues/31#issuecomment-985726174

When we export references in BibXML format, we have to change these:

* "World Wide Web Consortium" => "W3C", for the abbreviation we still keep "W3C"
* "Institute of Electrical and Electronics Engineers" => "IEEE", for the abbreviation we still keep "IEEE"

i.e. instead of this
```xml
<organization abbrev="IEEE">Institute of Electrical and Electronics Engineers</organization>
<organization abbrev="W3C"> World Wide Web Consortium </organization>
```

We should export this:
```xml
<organization abbrev="IEEE">IEEE</organization>
<organization abbrev="W3C"> W3C </organization>
```

**Comment by andrew2net** [comment]
fixed in relaton-bib -v 1.9.18

**Comment by ronaldtse** [comment]
@andrew2net we **only** want to change this behavior for BibXML output, not all Relaton output. i.e. Please do not change this behavior for other output formats.

**Comment by andrew2net** [comment]
@ronaldtse it's exactly what we have now. IEEE and W3C are used as company names in BibXML output only.
There is remains one question: should we do back transformation when we parse BibXML?

**Comment by ronaldtse** [comment]
@andrew2net yes, we should do the back transformation when parsing BibXML. Thanks!
