### ISSUE TITLE
Cleanup of fetched abstract from IETF

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#50]
https://github.com/ietf-ribose/relaton-data-ids/blob/876920b81794d9a5972f5d2c3381e9f8eff9b43b/data/DRAFT-3K1N-6TISCH-ALICE0-00.yaml#L73-L82

```yaml
abstract:
  content: "\n\t <p>   This document describes the limitation of present TSCH cell\n
    \  scheduling methods which use centralized or decentralized approach.\n   It
    firstly overview pros and cons of various cell scheduling\n   approaches including
    centralized, decentralized and autonomous TSCH\n   cell scheduling methods. It
    also suggest design considerations on\n   devising autonomous scheduling approach
    to avoid unexpected\n   confliction and increase channel utilization. For the
    last, it\n   provides one example that reflects all design considerations\n   mentioned.\n\n\n\t
    </p>\n      "
```

The content here is not very useable. Imagine that I have a software that uses this abstract, and I will be forced to clean up the double whitespaces, useless line breaks, trailing tabs/empty lines.

While we have not decided on the format of this text field, we should remove all these unnecessary artifacts.

**Comment by andrew2net** [comment]
fixed in -v 1.9.7
