### ISSUE TITLE
Remove “rfc-anchor” from doc identifier

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#52]
There is no docidentifier type called “rfc-anchor”. This is causing https://github.com/ietf-ribose/bibxml-service/issues/53.

**Comment by andrew2net** [comment]
fixed in -v 1.9.7

**Comment by ronaldtse** [comment]
@andrew2net also need to remove this identifier from the existing ietf-ribose datasets:
* [x] relaton-data-misc
* [x] relaton-data-ids
* [x] relaton-data-rfcs
* [x] relaton-data-rfcsubseries

Thanks!
