### ISSUE TITLE
RFC dates are too unspecific

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#54]
From @strogonoff  (https://github.com/ietf-ribose/relaton-data-rfcs/issues/4)

> According to Relaton model, we expect an ISO 8601 datetime string:
>
> https://github.com/relaton/relaton-models/blob/main/models/DateTime.lutaml#L11
>
> Now that BibXML service is doing some validation, dates in the RFCs source are failing it because they are too unspecific (for example, "2005-03").
>
> Can we add specificity by setting them at least to the first day of the month?

**Comment by ronaldtse** [comment]
> According to Relaton model, we expect an ISO 8601 datetime string:

ISO 8601-2 supports "unspecified" digits:

<img width="563" alt="Screenshot 2022-01-07 at 9 04 54 AM" src="https://user-images.githubusercontent.com/11865/148474524-6eb912cd-bcfb-442d-a46b-9fddc875c9ac.png">

We could use this.

> Can we add specificity by setting them at least to the first day of the month?

That will break the model. We have come across Relaton dates that only have year and cannot be further specified.

**Comment by strogonoff** [comment]
I believe we need to update the grammar[0] as well? I don’t think the regex allows for “XX” values.

https://github.com/relaton/relaton-models/blob/369b88802ac768524e1463139cc4f49ef3c1e30b/grammars/biblio.rnc#L24

**Comment by andrew2net** [comment]
@ronaldtse @strogonoff could we close this issue?

**Comment by ronaldtse** [comment]
This issue is not fixed. We need to represent the correct date and with the correct specificity. We have to update the schema as appropriate.

**Comment by ronaldtse** [comment]
> I believe we need to update the grammar[0] as well? I don’t think the regex allows for “XX” values.
> 
> https://github.com/relaton/relaton-models/blob/369b88802ac768524e1463139cc4f49ef3c1e30b/grammars/biblio.rnc#L24

Yes we should update the grammar.

**Comment by andrew2net** [comment]
@ronaldtse I just checked the regex expression in the grammar. It allows unspecific dates https://regex101.com/r/QV1TPS/1

**Comment by ronaldtse** [comment]
That's great, thanks @andrew2net !

**Comment by strogonoff** [comment]
@andrew2net So regex allows for dates like `2005-03-XX`? That’s great. Now seems like we only need to change the actual data so that date format matches ISO 8601 4.6.3

**Comment by ronaldtse** [comment]
Yes we will need to update the data, and also update the date parsing mechanism.

**Comment by strogonoff** [comment]
I expect date parsing in BibXML service (provided by Pydantic) _should_ continue working for unspecific dates with XX instead of day (since this complies with ISO 8601), if not then I can provide/adjust custom validator.

**Comment by andrew2net** [comment]
> @andrew2net So regex allows for dates like `2005-03-XX`? That’s great. Now seems like we only need to change the actual data so that date format matches ISO 8601 4.6.3

@strogonoff the regexp matches only `2005-03`. You can see it here https://regex101.com/r/QV1TPS/2
We need to ask @opoudjis to change the grammar.

**Comment by strogonoff** [comment]
> > @andrew2net So regex allows for dates like `2005-03-XX`? That’s great. Now seems like we only need to change the actual data so that date format matches ISO 8601 4.6.3
> 
> @strogonoff the regexp matches only `2005-03`. You can see it here https://regex101.com/r/QV1TPS/2 We need to ask @opoudjis to change the grammar.

ISO 8601 doesn’t allow `2005-03`, it requires `2005-03-XX`.

Regexp allows `2005-03-XX`. It just ignores the XX.

So we can simply update the data. But we can confirm with Nick first.

**Comment by ronaldtse** [comment]
Ah! Good question that I had to search for...

ISO 8601-1:2019 supports the "yyyy-mm" pattern:
<img width="821" alt="Screenshot 2022-03-29 at 7 59 17 PM" src="https://user-images.githubusercontent.com/11865/160606343-6a9e6f7a-9435-4092-b057-6fa145209386.png">

ISO 8601-2:2019 supports the "unspecified form" of "yyyy-mm-xx" pattern:
<img width="796" alt="Screenshot 2022-03-29 at 8 00 49 PM" src="https://user-images.githubusercontent.com/11865/160606600-891f4db4-6ab2-4738-a868-cc3ac073e628.png">

Either would be fine.

**Comment by strogonoff** [comment]
> ISO 8601-1:2019 supports the "yyyy-mm" pattern:

Ah.

**Comment by strogonoff** [comment]
I’ll look into the parser on my side and confirm whether a change if needed. If YYYY-MM is allowed by ISO8601, this raises the possibility of parser being non-compliant. 🤦‍♂️

**Comment by strogonoff** [comment]
> ISO 8601-1:2019 supports the "yyyy-mm" pattern:

I wonder if there is a semantic difference between “this date references given month” or “this date references an unspecific day within given month”. But it sounds more and more like bikeshedding.

**Comment by ronaldtse** [comment]
There is a semantic difference.

* "yyyy-mm" means "year yyyy, month mm". The smallest specification time scale unit is "month".

* "yyyy-mm-xx" means "year yyyy, month mm, day unknown". The smallest specification time scale unit is "day". It means a date that happened on a particular day that was unknown.

So it depends on whether we want to say, it was published in this month, vs it was published in a day in this month.

Maybe the first is more accurate.

**Comment by strogonoff** [comment]
Probably beyond the scope to know whether publication procedure took a month or it was some particular day. (I should’ve read the standard more carefully, perhaps I was looking at the wrong version…)

**Comment by ronaldtse** [comment]
@andrew2net is this still a problem? Are we setting the publication dates properly?

**Comment by andrew2net** [comment]
@ronaldtse Relaton stores dates as they are in a source data. It could be "yyyy", "yyyy-mm", or "yyyy-mm-dd". Relaton doensn't add X to unspecific dates. Should it add?

**Comment by ronaldtse** [comment]
> @ronaldtse Relaton stores dates as they are in a source data. It could be "yyyy", "yyyy-mm", or "yyyy-mm-dd". Relaton doensn't add X to unspecific dates. Should it add?

No need to add. If there's nothing left to do here can you please close it? Thanks.
