### ISSUE TITLE
(URGENT) Update fetch data source for Internet-Drafts to use new IETF rsync endpoint

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#55]
The public endpoint provided by IETF is:
* `rsync rsync.ietf.org::bibxml-ids`

We can implement a workflow like this:
https://github.com/ietf-ribose/bibxml-data-archive-sync/tree/main/.github/workflows

**Comment by andrew2net** [comment]
@ronaldtse do you mean we need to use the new source in `ietf-ribose/relaton-data-ids` and `ietf-ribose/bibxml-data-ids` repos?

**Comment by ronaldtse** [comment]
@andrew2net correct. The old source will be going away soon. The new one will be updated daily.
