### ISSUE TITLE
(URGENT) `author` element missing attributes `initials` and `surname`, missing `organization` element within

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#58]
From: https://github.com/ietf-ribose/bibxml-service/issues/88

> Compare
> https://dev.bibxml.org/api/v1/ref/rfcs/RFC8126/?format=bibxml
> and
> https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcs/reference.RFC.8126.xml
> 
> Note that keywords do not appear in what we currently provide for RFC bibxml.
> 
> This service should also not provide keywords in RFC bibxml initially. We may choose to add them to the bibxml in the future, but the initial deployment should match what is currently available.

Correct (old):
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcs/reference.RFC.8126.xml
```xml
<author initials="M." surname="Cotton" fullname="M. Cotton">
<organization/>
</author>
<author initials="B." surname="Leiba" fullname="B. Leiba">
<organization/>
</author>
<author initials="T." surname="Narten" fullname="T. Narten">
<organization/>
</author>
```

`author` element missing attributes `initials` and `surname`, and missing the empty `organization` element (new):
https://dev.bibxml.org/api/v1/ref/rfcs/RFC8126/?format=bibxml
```xml
<author fullname="M. Cotton"/>
<author fullname="B. Leiba"/>
<author fullname="T. Narten"/>
```

**Comment by andrew2net** [comment]
@ronaldtse do we relay need empty organization tags?

**Comment by ronaldtse** [comment]
@andrew2net yes let's include them. Without those we might be breaking some xml2rfc implementations.
