### ISSUE TITLE
(URGENT) Do not provide `day` attribute for RFCs, but keep it for Internet-Drafts

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#61]
IETF requested in ietf-ribose/bibxml-service#85 that we should not specify the `day` number for the publication date for RFCs.

This only applies to the RFC series -- the Internet-Drafts should still have `day`.

> Compare
> https://dev.bibxml.org/api/v1/ref/rfcs/RFC8126/?format=bibxml
> and
> https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcs/reference.RFC.8126.xml
> 
> Note that the later does not claim day=1
> 
> RFCs are published with a Year and Month, but not a day*. Please remove day from this rendering for RFCs (day still makes sense for Internet-Drafts).
> 
> *April 1st RFCs are published with a day in the header, but to date, the bibxml for them does not contain the day. It is not a requirement for this project to put a day in the bibxml for April 1 RFCs, but we may choose to work on this ourselves as a future enhancement. Note that not all RFCs published on April 1 are April 1st RFCs.

**Comment by andrew2net** [comment]
@ronaldtse days don't present in the data source. The day appeared due to a bug. I fixed it already https://github.com/ietf-ribose/bibxml-data-rfcs/blob/main/data/RFC8126.xml
If a source doesn't contain days then the output won't either.
