### ISSUE TITLE
(URGENT) Use `rfc` for `docid.type` for RFC documents

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#62]
From https://github.com/ietf-ribose/bibxml-service/issues/59

IETF has indicated that:
* The publisher of RFC is "The RFC Publisher", not "IETF".
* "Many of the RFCs in the series do not come from the IETF"
* "The IETF, IRTF, IAB, and Independent streams are the current sources of RFCs, as defined in RFC8728. Figure 1 may help you. But be aware that the model is likely to change soon - see https://datatracker.ietf.org/doc/draft-iab-rfcefdp-rfced-model/ where the Publisher is formally rolled into the RPC."
* "the series should simply be called "RFC""

`docid.type` indicates the "document ID scheme". An organization may have one or more "DocID schemes" (or we call them "PubID schemes").

For all RFC documents, we should use `rfc` as the `docid.type`.

**Comment by andrew2net** [comment]
Currently, this gem sets `docid.type` to "IETF" for all documents it fetches. To resolve this issue we need to detect `docid.type` from the reference somehow. Do we have completed list of types that will be fetched by this gem?

**Comment by andrew2net** [comment]
fixed in v 1.10.0
