### ISSUE TITLE
(URGENT) Use "3GPP" as organization name in BibXML serialization for "3rd Generation Partnership Project"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#63]
When serialising to BibXML, we only use the name "3GPP" without the full name, and not setting the abbreviation (similar to the situation with W3C).

This is similar to https://github.com/relaton/relaton-ietf/issues/48.

Linked to https://github.com/relaton/relaton-3gpp/issues/7

**Comment by andrew2net** [comment]
fixed in relaton v 1.10.0
