### ISSUE TITLE
Remove the "Place" attribute for RFCs, RFC subseries, and Internet-Drafts

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#64]
As per https://github.com/ietf-ribose/bibxml-service/issues/112, we should remove the "Place" attribute for RFCs, RFC subseries, and Internet-Drafts.

**Comment by andrew2net** [comment]
The only place "Fremont, CA" was added to any document fetched by this gem. Now it's removed.
@ronaldtse let me know if we need to add places for 3GPP and IEEE documents fetching by this gem.

**Comment by ronaldtse** [comment]
OK thanks, fixed in 9a7adefa23cac0fb8e726e3b40e22aae6075a427
