### ISSUE TITLE
URGENT: RFC bibxml should not specify document day

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#66]
From: https://github.com/ietf-ribose/bibxml-service/issues/85

-----

Compare
https://dev.bibxml.org/api/v1/ref/rfcs/RFC8126/?format=bibxml
and
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcs/reference.RFC.8126.xml

Note that the later does not claim `day=1`

RFCs are published with a Year and Month, but not a day*. Please remove day from this rendering for RFCs (day still makes sense for Internet-Drafts).

*April 1st RFCs are published with a day in the header, but to date, the bibxml for them does not contain the day. It is not a requirement for this project to put a day in the bibxml for April 1 RFCs, but we may choose to work on this ourselves as a future enhancement. Note that not all RFCs published on April 1 are April 1st RFCs.

**Comment by andrew2net** [comment]
@ronaldtse we've removed day already https://github.com/ietf-ribose/bibxml-data-rfcs/blob/8184e3081a7960f2ff601cdac4c86d563fe843d1/data/RFC8126.xml#L13

**Comment by ronaldtse** [comment]
Thanks for checking! Closing.
