### ISSUE TITLE
URGENT: Remove `<keywords>` value from BibXML files

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#67]
In Relaton we can keep the keywords. However, in BibXML, it has been clarified by IETF in https://github.com/ietf-ribose/bibxml-service/issues/88 that they do not support the `<keyword>` element yet.

We have to drop all keywords in the BibXML format.

We will add them back when IETF xml2rfc supports them in the future.

**Comment by andrew2net** [comment]
@ronaldtse we've removed keywords already https://github.com/ietf-ribose/bibxml-data-rfcs/blob/main/data/RFC8126.xml

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
