### ISSUE TITLE
URGENT: `<seriesinfo>` should render outside `<front>`

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#68]
From https://github.com/ietf-ribose/bibxml-service/issues/86:

-----

Compare
https://dev.bibxml.org/api/v1/ref/rfcs/RFC8126/?format=bibxml
and
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcs/reference.RFC.8126.xml

Note where seriesinfo differs in the two renderings.

While both are valid v3 xml, the second is preferred. Please change the renderer to follow that form.

**Comment by andrew2net** [comment]
@ronaldtse it's done some time ago https://github.com/ietf-ribose/bibxml-data-rfcs/blob/main/data/RFC8126.xml

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
