### ISSUE TITLE
URGENT: Use "RFC", "Internet-Draft" for document identifier type instead of "IETF"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#70]
As requested in https://github.com/ietf-ribose/bibxml-service/issues/59#issuecomment-1046281131, the IETF has requested the DocID type to be named:

* For RFCs, the type should be "RFC" (or "rfc")
* For Internet-Drafts, the type should be "Internet-Draft" (or "internet-draft")
* For RFC subseries, the type is not yet requested but likely also "RFC" (pending confirmation in https://github.com/ietf-ribose/bibxml-service/issues/59)

The DocID type should no longer say "IETF".

This is a change that will affect Metanorma, ping @opoudjis .

**Comment by andrew2net** [comment]
@ronaldtse for RFC and RFC subseries it's already done https://github.com/relaton/relaton-ietf/issues/62

**Comment by andrew2net** [comment]
The "Internet-Dreaft" documents have an `anchor` attribute and `seriesInfo` element with `name="Internet-Draft"` attribute https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.3k1n-6tisch-alice0.xml
```xml
<reference anchor="I-D.3k1n-6tisch-alice0">
  <front>
    <title>Autonomous Link-based TSCH Cell Scheduling</title>
    <author initials="S" surname="Kim" fullname="Seohyang Kim">
      <organization/>
    </author>
    <author initials="N" surname="Kim" fullname="Na Kim">
      <organization/>
    </author>
    <author initials="N" surname="Lam" fullname="Nguyen Lam">
      <organization/>
    </author>
    <author initials="S" surname="University" fullname="Seoul University">
      <organization/>
    </author>
    <date month="December" day="15" year="2016"/>
    <abstract>
      <t>This document describes the limitation of present TSCH cell scheduling methods which use centralized or decentralized approach. It firstly overview pros and cons of various cell scheduling approaches including centralized, decentralized and autonomous TSCH cell scheduling methods. It also suggest design considerations on devising autonomous scheduling approach to avoid unexpected confliction and increase channel utilization. For the last, it provides one example that reflects all design considerations mentioned.</t>
    </abstract>
  </front>
  <seriesInfo name="Internet-Draft" value="draft-3k1n-6tisch-alice0-01"/>
  <format type="TXT" target="http://www.ietf.org/internet-drafts/draft-3k1n-6tisch-alice0-01.txt"/>
</reference>
```
Currently, we use the anchor to produce primary PubID. The `seriesInfo` is saved as `type="Internet-Draft"` docidentifier:
```xml
<bibdata type="standard">
  <fetched>2022-02-21</fetched>
  <title format="text/plain" language="en" script="Latn">Autonomous Link-based TSCH Cell Scheduling</title>
  <uri type="xml">https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.I-D.3k1n-6tisch-alice0.xml</uri>
  <uri type="TXT">http://www.ietf.org/internet-drafts/draft-3k1n-6tisch-alice0-01.txt</uri>
  <docidentifier type="IETF" primary="true">I-D 3k1n-6tisch-alice0</docidentifier>
  <docidentifier type="IETF" scope="anchor">I-D.3k1n-6tisch-alice0</docidentifier>
  <docidentifier type="Internet-Draft">draft-3k1n-6tisch-alice0-01</docidentifier>
  ...
```
Should we use the `<docidentifier type="Internet-Draft">draft-3k1n-6tisch-alice0-01</docidentifier>` as primary PubID and remove `<docidentifier type="IETF" primary="true">I-D 3k1n-6tisch-alice0</docidentifier>`?

**Comment by ronaldtse** [comment]
@andrew2net we have received clarification from IETF:

`Internet-Draft` identifiers can only be one of:

* `3k1n-6tisch-alice0` (no version)
* `draft-3k1n-6tisch-alice0-{version}` (with version)

When people cite, they only have these two options.

> Should we use the `<docidentifier type="Internet-Draft">draft-3k1n-6tisch-alice0-01</docidentifier>` as primary PubID and remove `<docidentifier type="IETF" primary="true">I-D 3k1n-6tisch-alice0</docidentifier>`?

Yes please.

> `<seriesInfo name="Internet-Draft" value="draft-3k1n-6tisch-alice0-01"/>`

Should be this instead:
```
<seriesInfo name="Internet-Draft" value="3k1n-6tisch-alice0"/>
```

**Comment by andrew2net** [comment]
> > `<seriesInfo name="Internet-Draft" value="draft-3k1n-6tisch-alice0-01"/>`
> 
> Should be this instead:
> 
> ```
> <seriesInfo name="Internet-Draft" value="3k1n-6tisch-alice0"/>
> ```

@ronaldtse are you sure? The [original document](https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.draft-3k1n-6tisch-alice0-01.xml) contains `<seriesInfo name="Internet-Draft" value="draft-3k1n-6tisch-alice0-01"/>`

**Comment by ronaldtse** [comment]
@andrew2net Ah! You're right -- seriesInfo is for displaying the exact draft name within that series.  OK we keep it that way...

**Comment by andrew2net** [comment]
@ronaldtse is it ok if we have primary PubIDs duplicates? For example, the following documents will have identical PubID:

https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.draft-zzhang-teas-rmr-rsvp-p2mp-00.xml
https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.draft-zzhang-teas-rmr-rsvp-p2mp-01.xml
https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.draft-zzhang-teas-rmr-rsvp-p2mp-02.xml

**Comment by ronaldtse** [comment]
@andrew2net I thought they were not identical? `draft-zzhang-teas-rmr-rsvp-p2mp-00` is the versioned Internet-Draft identifier, `zzhang-teas-rmr-rsvp-p2mp` is the unversioned Internet-Draft identifier (similar to ISO 9001:2005 vs ISO 9001)
