### ISSUE TITLE
URGENT: Internet-Draft references in BibXML format missing `target` to information resources

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#71]
e.g. https://github.com/ietf-ribose/bibxml-data-ids/blob/main/data/draft--pale-email-00.xml

```xml
<reference anchor="I-D.-pale-email">
  <front>
    <title>Forming Intuitive Email Addresses</title>
    <author fullname="Predrag Pale" initials="P." surname="Pale">
      <organization/>
    </author>
    <author fullname="Kristijan Cerovski" initials="K." surname="Cerovski">
      <organization/>
    </author>
    <date year="2004" month="March"/>
    <abstract>
      <t>This memo presents a proposal for an efficient and simple way of forming email addresses. The goal is to achieve easier, more productive communication between email users, in particular by aking addresses intuitive and thus easy to remember, or guess-enabled on material-world data about the correspondent, as well as independent from technical or organizational specifics of email services.</t>
    </abstract>
  </front>
  <seriesInfo name="Internet-Draft" value="draft--pale-email-00"/>
</reference>
```

This is missing the `<reference ... anchor="...">` `anchor` attribute.

This data is present in the Relaton YAML version:
https://github.com/ietf-ribose/relaton-data-ids/blob/01638f583ad43a9124c17247289bf1683a136237/data/draft--pale-email-00.yaml#L11
```yaml
link:
- content: https://www.ietf.org/archive/id/draft--pale-email-00.txt
  type: TXT
```

The first line should be:
```xml
<reference anchor="I-D.-pale-email" target="https://www.ietf.org/archive/id/draft--pale-email-00.txt">
```

This issue does not happen with RFC or RFC subseries in BibXML format.

**Comment by andrew2net** [comment]
@ronaldtse the source dataset `rsync.ietf.org::bibxml-ids`doesn't contain a `target` element:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<reference anchor="I-D.-pale-email">
   <front>
      <title>Forming Intuitive Email Addresses</title>
      <author initials="P." surname="Pale" fullname="Predrag Pale">
         </author>
      <author initials="K." surname="Cerovski" fullname="Kristijan Cerovski">
         </author>
      <date month="March" day="2" year="2004" />
      <abstract>
	 <t>   This memo presents a proposal for an efficient and simple way of 
   forming email addresses.  The goal is to achieve easier, more 
   productive communication between email users, in particular by aking 
   addresses intuitive and thus easy to remember, or guess-enabled on 
   material-world data about the correspondent, as well as independent 
   from technical or organizational specifics of email services. 

	 </t>
      </abstract>
   </front>
   <seriesInfo name="Internet-Draft" value="draft--pale-email-00" />
   <format type="TXT" target="https://www.ietf.org/archive/id/draft--pale-email-00.txt" />
</reference>
```
It contains the `format` element with link of `TXT` type. Currently, Relaton renders link with `src` type as a `target` element. We can use any other type of link to create target but when we parse BibXml the `target` will be treated as `src` link. Wouldn't it be a problem?
Should we add the `format` element with the link?

UPD FYI `format` element is deprecated https://datatracker.ietf.org/doc/html/rfc7991#section-3.3
UPD 2 the `target` page doesn't exist https://www.ietf.org/archive/id/draft--pale-email-00.txt

**Comment by ronaldtse** [comment]
@andrew2net this is a good find. The IETF just gave guidance here: https://github.com/ietf-ribose/bibxml-service/issues/142#issuecomment-1046999571 that:
* for I-Ds, use `<format>`
* for RFCs, use `<reference target="...">`

For now. Feel free to close if we are compliant. Thanks.

NOTE: Yes I also found that the `target` page for I-Ds often do not exist.
