### ISSUE TITLE
Create individual files for every unversioned I-D instance

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#76]
From https://github.com/ietf-ribose/relaton-data-ids/issues/16 by @strogonoff 

For every `draft-xxx-nn`, we create individual bibliographic items for every unversioned instance `draft-xxx` that contains relationships using the `contains` relationship to the individual versioned drafts (`draft-xxx-nn`).

This will provide an `index` for software to know the full series of an I-D without needing to find individual version files.

Related attempts to address similar discovery issues:

- https://github.com/ietf-ribose/relaton-data-ids/issues/6
- https://github.com/ietf-ribose/relaton-data-ids/issues/15

**Comment by strogonoff** [comment]
I don’t mind creating an unversioned item for each unversioned I-D and use it as series.

Note though it is not a requirement for series to be defined as a separate bibitem, we have plenty of series among Relaton datasets that do not have their own separate bibitems (and BibXML service converts those to links just fine):

- [W3C NOTE](https://github.com/relaton/relaton-data-w3c/blob/291c54e41949c7e261f96b628577ae9115d5bb75/data/NOTE-IMAGEMAP.yaml#L23-L27) — see https://dev.bibxml.org/get-one/by-docid/?docid=W3C+NOTE-imagemap&doctype=W3C

- [NIST](https://github.com/relaton/relaton-data-nist/blob/983391af540e660f9ff3609b74b18be3560f8703/data/NIST_CSWP_02042022-5.yaml#L37-L41) — see https://dev.bibxml.org/get-one/by-docid/?docid=NIST+CSWP+02042022-5&doctype=NIST

**Comment by ronaldtse** [comment]
> we have plenty of series among Relaton datasets that do not have their own separate bibitems

W3C NOTE is not a series, it's a document type. W3C items are going to be separately encoded as versioned vs unversioned entries.

NIST CSWP is a proper "series" but it is not commonly cited in the way of versioned vs unversioned, dated vs undated.

**Comment by strogonoff** [comment]
I’m just setting the priorities. Specifying series can be done first, and unversioned bibitem YAML files could be created later. (Since there are precedents where series don’t have separate bibitems in current YAML data, and it works fine for BibXML service and does not violate Relaton spec.)

> NIST CSWP is a proper "series" but it is not commonly cited in the way of versioned vs unversioned, dated vs undated.

We don’t have NIST CSWP as series, we have only global NIST series. (This is actually a problem, filed https://github.com/ietf-ribose/relaton-data-nist/issues/5.)

**Comment by ronaldtse** [comment]
@strogonoff While the "NIST CSWP publication series" (and the other 50+ publication series) can technically be citable, we don't need to make it citable at this stage because there is just no practice that uses it today. For sure IETF will not need them.

**Comment by ronaldtse** [comment]
Relevant to https://github.com/relaton/relaton-ietf/issues/74

**Comment by andrew2net** [comment]
> For every `draft-xxx-nn`, we create individual bibliographic items for every unversioned instance `draft-xxx` that contains relationships using the `contains` relationship to the individual versioned drafts (`draft-xxx-nn`).

@ronaldtse `contains` isn't allowed as relation type in the [grammar](https://github.com/relaton/relaton-models/blob/cee86293102834b42a928f64e1e70d38cee393f3/grammars/biblio.rnc#L383). In the relaton-iso we use `instance`.

**Comment by strogonoff** [comment]
I think rfcsubseries uses "includes", too

**Comment by ronaldtse** [comment]
@andrew2net `instance` is for a physical instance so we shouldn't use that. Then we use `include/includedIn`.
