### ISSUE TITLE
RFC subseries: link pointing to `https://raw.githubusercontent.com/relaton/relaton-data-ietf/...` should be removed

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#77]
https://github.com/ietf-ribose/relaton-data-rfcsubseries/blob/d3fe30d9e5860f9e4c6fef815fda5fd9ec52c3b9/data/BCP0048.yaml#L37-L41

The link:
```yaml
    - content: https://raw.githubusercontent.com/relaton/relaton-data-ietf/master/data/reference.RFC.3150.xml
      type: xml
```

Should no longer exist, because this is not an authoritative source. 

Let's remove it.

**Comment by andrew2net** [comment]
fixed
