### ISSUE TITLE
`version.draft` should not be a list?

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-ietf#84]
Regarding: https://github.com/ietf-ribose/relaton-data-ids/blob/7e90bafefe9b579ddfa339169d5ffbe949e548f1/data/draft-3k1n-6tisch-alice0-00.yaml#L90-L92

According to the model, `version.draft` can contain either one string or nothing: https://github.com/relaton/relaton-models/blob/f3363d495c7da9987fd2eb91a5c958284cfb43c3/models/VersionInfo.lutaml#L10-L14

Unless we foresee a change which makes `version.draft` eligible for multiple values, we should not use a list for that probably.

**Comment by ronaldtse** [comment]
I'm not sure about the purpose of the `version.draft` attribute. @opoudjis @andrew2net can you help clarify?

**Comment by strogonoff** [comment]
@ronaldtse Definition is here:

https://github.com/relaton/relaton-models/blob/f3363d495c7da9987fd2eb91a5c958284cfb43c3/models/VersionInfo.lutaml#L10-L14

I believe the purpose is to introduce a marker that actually represents a version of a draft, previously we did not have a structured property denoting I-D version.

**Comment by andrew2net** [comment]
@strogonoff the [grammar](https://github.com/relaton/relaton-models/blob/ec12a0b5f00fd9e5dd19a63e6d0e1658d0165331/grammars/biblio.rnc#L467-L470) defines `version.draft` as list. I use the gramma as a reliable model description because @opoudjis is supporting it and it's possible to test RelatonXML outputs against grammas.

**Comment by strogonoff** [comment]
Based on https://github.com/relaton/relaton-models/issues/39#issuecomment-1139518377, we should probably make `version` a list and update RNC grammar…

**Comment by ronaldtse** [comment]
@andrew2net this is an urgent issue that blocks the usage of the bibxml-service. Can you proceed with the fix ASAP? Thanks!
