### ISSUE TITLE
Correct format for primary `docid` of unversioned containers

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-ietf#85]
Currently, primary `docid` for unversioned I-D looks like this:

https://github.com/ietf-ribose/relaton-data-ids/blob/7e90bafefe9b579ddfa339169d5ffbe949e548f1/data/draft-3k1n-6tisch-alice0.yaml#L10-L13

    draft-3k1n-6tisch-alice0

However, IETF mentioned that correct format _without a version_ must look like:

    I-D.3k1n-6tisch-alice0

Just want to confirm whether I can expect a change, this is relevant to automated xml2rfc path resolution in BibXML service.

**Comment by ronaldtse** [comment]
The IAB (governing body of IETF and RFC series) has clarified the following.

The primary PubID is ONLY one of:
* `draft-xxx` (unversioned)
* `draft-xxx-nnn` (versioned)

The `I-D.3k1n-6tisch-alice0` ID is an "implementation detail", it is NOT authoritative. 

This means we should remove it from the Relaton IETF model entirely. @andrew2net can you please help?

In addition, it is up to the BibXML Service to interpret `I-D.3k1n-6tisch-alice0` as `draft-3k1n-6tisch-alice0` and to serve that identifier in the BibXML anchor. Is this alright with you @strogonoff ?

**Comment by strogonoff** [comment]
OK, my assumption was incorrect, the `I-D.` format is only for legacy xml2rfc-style paths apparently.

@ronaldtse we don’t need to remove a non-primary `anchor` docid. In fact, the anchor docid is _used_ by BibXML service when formatting `<reference>` anchors. My concern was only about the `primary` docid used for citations and unambiguously referencing an I-D.

**Comment by strogonoff** [comment]
> In addition, it is up to the BibXML Service to interpret I-D.3k1n-6tisch-alice0 as draft-3k1n-6tisch-alice0 and to serve that identifier in the BibXML anchor. Is this alright with you @strogonoff?

This is OK with me, let’s do it. Are we filing another issue or editing this one?

**Comment by ronaldtse** [comment]
@strogonoff Feel free to repurpose this one?

**Comment by strogonoff** [comment]
Okay, after consideration I am creating a new one. This issue needs no change.
