### ISSUE TITLE
Expand rfcbib coverage beyond ID, RFC?

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-ietf#9]
Not a given, but: xml2rfc.ietf.org/public/rfc hosts a bunch of other specifications' bibliography: W3C, XSF, IEEE, Miscellaneous. They are not exhaustive lists of references from those specs. Should we offer the option of retrieving references from those specs as well?

**Comment by ronaldtse** [comment]
@opoudjis all the non-IETF bibliographic references are incomplete and often outdated. I prefer we don't touch those. In particular, W3C and IEEE ones can be retrieved authoritatively elsewhere. Would be a matter of W3Cbib and IEEEbib.
