### ISSUE TITLE
Unversioned I-D item “includes” versions of different Internet Drafts

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-ietf#90]
https://github.com/ietf-tools/relaton-data-ids/blob/cd250b155e0ce902bc32675bca3792c62a6c7830/data/draft-hartman-webauth.yaml#L33-L53

Are we sure that draft-hartman-webauth-00 and draft-hartman-webauth-phishing-09 are versions of the same draft? The titles are different… (https://dev.bibxml.org/get-one/by-docid/?docid=draft-hartman-webauth&doctype=Internet-Draft)

**Comment by ronaldtse** [comment]
We can only know the real succession of drafts from datatracker, because authors are required to manually indicate supersession of drafts. 

In the current case, it sounds like a bug with matching strings with regular expressions.
