### ISSUE TITLE
Missing unversioned I-D containers

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-ietf#91]
For most I-Ds we offer an unversioned “series” bibitem as well as a bibitem for each concrete I-D version.

For example: https://github.com/ietf-tools/relaton-data-ids/blob/main/data/draft-aa-ldp-link-shut.yaml and https://github.com/ietf-tools/relaton-data-ids/blob/main/data/draft-aa-ldp-link-shut-01.yaml.

However, for some items we only have the versioned bibitem. For example: https://github.com/ietf-tools/relaton-data-ids/blob/main/data/draft-avasarala-sipping-comm-div-notification-01.yaml

**Comment by ronaldtse** [comment]
> However, for some items we only have the versioned bibitem.

This should not happen? @andrew2net can you investigate?
