### ISSUE TITLE
(URGENT) "bibxml-data-misc" data source should not display publisher as IETF

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#93]
We need to remove `<author><organization abbrev="IETF">Internet Engineering Task Force</organization></author>` because the bibliographic item does not technically originate from IETF.

This is a blocker for:
* https://github.com/ietf-tools/relaton-data-misc/issues/15
* https://github.com/ietf-ribose/bibxml-service/issues/234

**Comment by andrew2net** [comment]
@ronaldtse I'm not sure what it needs to do here. The BibXML parser adds IETF as publisher type contributor for Internet-Drafts. Do we need to remove the contributor?

**Comment by ronaldtse** [comment]
> The BibXML parser adds IETF as publisher type contributor for Internet-Drafts.  

Actually, this issue is mistaken. Our current version of `relaton-data-misc` is correct.

Look at this data:
https://github.com/ietf-tools/relaton-data-misc/blob/fcc1aae9869668935f7823724e2f74f89c07332b/data/reference.PKCS.1.1991.yaml#L22-L27

There is no publisher IETF.

@strogonoff I suspect it is the BibXML service that is adding the IETF organization. Can you please confirm?

**Comment by ronaldtse** [comment]
I'm going to close this to prevent confusion.
