### ISSUE TITLE
Relations on rfcsubseries have malformed RFC IDs

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-ietf#96]
For example, here the relation says that there is a bibliographic item with primary docid equal to `RFC0791`:

https://github.com/ietf-tools/relaton-data-rfcsubseries/blob/78ea2b3ecf3b357d30038a6f38fdbbf9b03b9e85/data/STD0005.yaml#L26-L86

However, the bibliographic item has primary docid `RFC 791`:

https://github.com/ietf-tools/relaton-data-rfcs/blob/main/data/RFC0791.yaml#L11-L14

This seems to be the case with ALL rfcsubseries, and I think this causes https://github.com/ietf-ribose/bibxml-service/issues/250. The application is unable to resolve relations to actual bibliographic items, which contain metadata such as titles (`bibxml` serializer has no choice but to substitute `[title unavailable]`, since `<title>` is a mandatory element).

**Comment by andrew2net** [comment]
@strogonoff it seems I confused docids and references/filenames. It is obvious the identifiers should be with space after RFC and without leading zeros in a number. I'll fix it.

**Comment by strogonoff** [comment]
Thanks for quick fix!
