### ISSUE TITLE
(URGENT) "day" of publishing not always parsed correctly

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ietf#97]
Originally reported at:
* https://github.com/ietf-tools/bibxml-service/issues/265

Reported also at:
* https://github.com/ietf-tools/relaton-data-ids/issues/22

This is a bug in the Relaton BibXML parsing code. The data source is not parsing the "day" correctly:

https://github.com/ietf-tools/relaton-data-ids/blob/a2d55f1d00fd38720fcdf9d4383f2054a96be10d/data/draft-ietf-core-oscore-groupcomm-14.yaml#L24

The original BibXML from Datatracker shows the following:
```xml
      <date month="March" day="7" year="2022" />
```

Perhaps there is an assumption that day is always double digit while it also appears in single digits?

**Comment by andrew2net** [comment]
fixed in relaton-bib v 1.12.6
https://github.com/relaton/relaton-data-ids/blob/5a629ce8eb31f868ca8049e7ffa98524978e9c06/data/draft-ietf-core-oscore-groupcomm-14.yaml#L24

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
